BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
CREATE TABLE dbo.Evaluacion
	(
	id int NOT NULL,
	Nombre varchar(20) NOT NULL,
	fecha date NOT NULL,
	valorPorcentual decimal(2,2) NOT NULL,
	idRubro int not null
	) 
GO
ALTER TABLE dbo.Evaluacion ADD CONSTRAINT
	PK_Evaluacion PRIMARY KEY CLUSTERED (id) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
ALTER TABLE dbo.Evaluacion add constraint FK_Rubro foreign key (idRubro) references Rubro(id)
GO

COMMIT