insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (1, 'WHFBL', 'n/a', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (2, 'DFVL', 'Finance', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (3, 'CEN', 'n/a', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (4, 'COWN', 'Finance', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (5, 'PPHMP', 'Health Care', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (6, 'NGLS^A', 'n/a', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (7, 'CIZN', 'Finance', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (8, 'VTGN', 'Health Care', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (9, 'SZC', 'n/a', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (10, 'AFA', 'Finance', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (11, 'MITL', 'Technology', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (12, 'VTL', 'Health Care', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (13, 'IIPR', 'Finance', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (14, 'UAE', 'n/a', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (15, 'SHOR', 'Public Utilities', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (16, 'HK.WS', 'n/a', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (17, 'SEV', 'Energy', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (18, 'SCQ', 'n/a', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (19, 'DOC', 'Consumer Services', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (20, 'ABR^B', 'n/a', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (21, 'DGICA', 'Finance', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (22, 'WMC', 'Consumer Services', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (23, 'TNXP', 'Health Care', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (24, 'GRIF', 'Finance', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (25, 'ZIONW', 'Finance', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (26, 'LVHD', 'n/a', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (27, 'PRCP', 'Capital Goods', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (28, 'FENX', 'Consumer Services', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (29, 'AXARU', 'Finance', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (30, 'WSR', 'Consumer Services', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (31, 'FBZ', 'n/a', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (32, 'EACQW', 'Capital Goods', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (33, 'ERI', 'Consumer Services', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (34, 'PII', 'Capital Goods', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (35, 'KTEC', 'Technology', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (36, 'ABIL', 'Finance', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (37, 'T', 'Public Utilities', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (38, 'ENTG', 'Consumer Non-Durables', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (39, 'NOA', 'Energy', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (40, 'MFT', 'n/a', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (41, 'LBAI', 'Finance', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (42, 'SBBX', 'Finance', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (43, 'EGIF', 'n/a', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (44, 'NAUH', 'Consumer Services', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (45, 'CUBS', 'Finance', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (46, 'SRNE', 'Health Care', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (47, 'FTLB', 'n/a', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (48, 'CLIR', 'Capital Goods', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (49, 'LPI', 'Energy', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (50, 'SRCE', 'Finance', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (51, 'FTCS', 'n/a', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (52, 'LCAHW', 'Finance', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (53, 'KRC', 'Consumer Services', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (54, 'SCWX', 'Technology', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (55, 'BXE', 'Energy', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (56, 'NPTN', 'Technology', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (57, 'ESGG', 'n/a', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (58, 'DMLP', 'Energy', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (59, 'TNXP', 'Health Care', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (60, 'GEMP', 'Health Care', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (61, 'DSL', 'n/a', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (62, 'XHR', 'Consumer Services', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (63, 'OFG^D', 'n/a', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (64, 'BDJ', 'n/a', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (65, 'ZN', 'Energy', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (66, 'BFS^C', 'n/a', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (67, 'CLNS^I', 'n/a', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (68, 'CMCM', 'Technology', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (69, 'PXLW', 'Technology', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (70, 'NTGR', 'Public Utilities', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (71, 'SAR', 'n/a', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (72, 'CSA', 'n/a', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (73, 'HELE', 'Consumer Durables', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (74, 'CXP', 'Consumer Services', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (75, 'SHBI', 'Finance', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (76, 'GBX', 'Capital Goods', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (77, 'CIEN', 'Public Utilities', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (78, 'PK', 'Consumer Services', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (79, 'AZO', 'Consumer Services', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (80, 'CNA', 'Finance', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (81, 'EQT', 'Energy', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (82, 'TSO', 'Energy', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (83, 'AHT', 'Consumer Services', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (84, 'HRMNU', 'Public Utilities', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (85, 'BIOA', 'Basic Industries', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (86, 'FSNN', 'Technology', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (87, 'CUBE', 'Consumer Services', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (88, 'MCA', 'n/a', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (89, 'HCAP', 'n/a', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (90, 'OSUR', 'Health Care', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (91, 'IRDM', 'Consumer Durables', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (92, 'BT', 'Public Utilities', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (93, 'HCC', 'Energy', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (94, 'IFF', 'Basic Industries', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (95, 'BKN', 'n/a', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (96, 'AJRD', 'Capital Goods', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (97, 'LOXO', 'Health Care', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (98, 'CHY', 'n/a', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (99, 'CRZO', 'Energy', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (100, 'IHD', 'n/a', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (101, 'ACAD', 'Health Care', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (102, 'CLLS', 'Health Care', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (103, 'AREX', 'Energy', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (104, 'RWLK', 'Health Care', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (105, 'UBS', 'Finance', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (106, 'USM', 'Public Utilities', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (107, 'FNTE', 'Finance', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (108, 'GRAM', 'Basic Industries', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (109, 'ALP^O', 'Public Utilities', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (110, 'KREF', 'Consumer Services', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (111, 'SRUNW', 'Finance', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (112, 'BKN', 'n/a', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (113, 'AXR', 'Consumer Services', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (114, 'MX', 'Technology', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (115, 'JPM^F', 'n/a', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (116, 'CTHR', 'Consumer Durables', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (117, 'LTRPA', 'Technology', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (118, 'FI', 'Energy', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (119, 'AI^B', 'n/a', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (120, 'IPWR', 'Energy', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (121, 'CHKR', 'Energy', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (122, 'WRB^B', 'n/a', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (123, 'NURO', 'Health Care', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (124, 'TBNK', 'Finance', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (125, 'REGI', 'Basic Industries', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (126, 'RNP', 'n/a', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (127, 'NVMI', 'Capital Goods', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (128, 'PKO', 'n/a', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (129, 'CLIRW', 'Capital Goods', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (130, 'NWE', 'Public Utilities', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (131, 'HOG', 'Consumer Non-Durables', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (132, 'PGP', 'n/a', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (133, 'AIV', 'Consumer Services', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (134, 'DCTH', 'Health Care', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (135, 'HII', 'Capital Goods', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (136, 'AZPN', 'Technology', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (137, 'FCE.A', 'n/a', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (138, 'EQS', 'n/a', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (139, 'EEA', 'n/a', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (140, 'PRE^I', 'n/a', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (141, 'MSG', 'Consumer Services', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (142, 'SU', 'Energy', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (143, 'VTA', 'n/a', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (144, 'TSEM', 'Technology', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (145, 'SHPG', 'Health Care', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (146, 'RA', 'n/a', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (147, 'HNRG', 'Energy', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (148, 'GIGA', 'Capital Goods', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (149, 'BREW', 'Consumer Non-Durables', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (150, 'LENS', 'Health Care', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (151, 'KEY', 'Finance', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (152, 'IPG', 'Technology', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (153, 'ALXN', 'Health Care', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (154, 'DNP', 'n/a', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (155, 'SPKEP', 'Public Utilities', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (156, 'EXFO', 'Capital Goods', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (157, 'PKD', 'Energy', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (158, 'ENS', 'Consumer Non-Durables', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (159, 'GS^D', 'n/a', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (160, 'WDFC', 'Basic Industries', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (161, 'PYT', 'Finance', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (162, 'ELS^C', 'n/a', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (163, 'DTK', 'Finance', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (164, 'SBOW', 'Energy', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (165, 'BIP', 'Consumer Services', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (166, 'ZB^A', 'n/a', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (167, 'LENS', 'Health Care', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (168, 'PMT^A', 'n/a', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (169, 'IRET', 'Consumer Services', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (170, 'SND', 'n/a', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (171, 'AJRD', 'Capital Goods', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (172, 'OKS', 'Public Utilities', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (173, 'BLVD', 'Finance', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (174, 'VYMI', 'n/a', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (175, 'PLCE', 'Consumer Services', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (176, 'RTIX', 'Health Care', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (177, 'PBH', 'Health Care', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (178, 'NMI', 'n/a', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (179, 'LNT', 'Public Utilities', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (180, 'BPOPN', 'Finance', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (181, 'SPCB', 'Technology', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (182, 'MP^D', 'n/a', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (183, 'GTN', 'Consumer Services', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (184, 'IAC', 'Consumer Services', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (185, 'ONDK', 'Finance', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (186, 'RVSB', 'Finance', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (187, 'OFG^B', 'n/a', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (188, 'BEDU', 'Consumer Services', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (189, 'IT', 'Consumer Services', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (190, 'HFBC', 'Finance', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (191, 'GMLP', 'Consumer Services', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (192, 'CTRE', 'Consumer Services', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (193, 'BTO', 'n/a', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (194, 'C^P', 'n/a', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (195, 'TRP', 'Public Utilities', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (196, 'MIK', 'Consumer Services', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (197, 'HCHC', 'Capital Goods', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (198, 'Y', 'Finance', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (199, 'MELR', 'Finance', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (200, 'ALCO', 'Consumer Non-Durables', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (201, 'HK', 'Energy', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (202, 'MS^I', 'n/a', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (203, 'INVA', 'Health Care', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (204, 'MSP', 'n/a', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (205, 'CRT', 'Energy', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (206, 'GTN', 'Consumer Services', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (207, 'TTP', 'n/a', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (208, 'CIEN', 'Public Utilities', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (209, 'GFI', 'Basic Industries', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (210, 'QINC', 'n/a', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (211, 'FCEF', 'n/a', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (212, 'QINC', 'n/a', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (213, 'LM', 'Finance', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (214, 'CCBG', 'Finance', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (215, 'AJXA', 'Consumer Services', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (216, 'GYRO', 'Consumer Services', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (217, 'VR', 'Finance', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (218, 'HAL', 'Energy', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (219, 'GOODO', 'Consumer Services', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (220, 'FEP', 'n/a', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (221, 'TVC', 'Public Utilities', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (222, 'PCOM', 'Miscellaneous', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (223, 'VNET', 'Technology', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (224, 'NMR', 'Finance', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (225, 'CBM', 'Health Care', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (226, 'PSCM', 'n/a', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (227, 'SCMP', 'Health Care', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (228, 'ARQL', 'Health Care', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (229, 'LHO^J', 'n/a', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (230, 'PNC', 'Finance', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (231, 'AFB', 'n/a', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (232, 'HDNG', 'Capital Goods', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (233, 'CDEV', 'Energy', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (234, 'CFX', 'Capital Goods', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (235, 'DYNT', 'Health Care', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (236, 'PBR', 'Energy', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (237, 'SNDX', 'Health Care', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (238, 'SNY', 'Health Care', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (239, 'HUNTW', 'Transportation', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (240, 'ATH', 'Finance', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (241, 'JOE', 'Consumer Services', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (242, 'AHGP', 'Energy', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (243, 'CLIR', 'Capital Goods', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (244, 'SRPT', 'Health Care', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (245, 'BBY', 'Consumer Services', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (246, 'ALNY', 'Health Care', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (247, 'OLP', 'Consumer Services', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (248, 'RZB', 'Finance', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (249, 'MFV', 'n/a', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (250, 'OLLI', 'Consumer Services', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (251, 'FTV', 'Capital Goods', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (252, 'VNO^I', 'n/a', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (253, 'ACV', 'n/a', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (254, 'PFH', 'Finance', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (255, 'BOSC', 'Technology', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (256, 'TGS', 'Public Utilities', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (257, 'RCON', 'Energy', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (258, 'AGD', 'n/a', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (259, 'CRCM', 'Consumer Services', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (260, 'BRO', 'Finance', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (261, 'NTEC', 'Health Care', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (262, 'INDB', 'Finance', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (263, 'ELY', 'Consumer Non-Durables', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (264, 'HES^A', 'n/a', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (265, 'OCLR', 'Technology', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (266, 'DFIN', 'Consumer Services', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (267, 'HIX', 'n/a', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (268, 'PFIE', 'Energy', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (269, 'CADE', 'Finance', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (270, 'TUSK', 'Energy', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (271, 'MTP', 'Health Care', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (272, 'RNVAZ', 'Health Care', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (273, 'DS', 'Consumer Services', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (274, 'CMCM', 'Technology', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (275, 'QQQ', 'n/a', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (276, 'MPVD', 'Basic Industries', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (277, 'CBLI', 'Health Care', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (278, 'EARN', 'Consumer Services', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (279, 'IPXL', 'Health Care', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (280, 'TI', 'Consumer Services', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (281, 'NESR', 'Finance', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (282, 'CFRX', 'Health Care', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (283, 'VVUS', 'Health Care', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (284, 'TPL', 'Energy', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (285, 'CFO', 'n/a', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (286, 'NUV', 'n/a', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (287, 'FOE', 'Basic Industries', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (288, 'CPAA', 'Finance', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (289, 'PIR', 'Consumer Services', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (290, 'PBI^B', 'n/a', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (291, 'SHOO', 'Consumer Non-Durables', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (292, 'CHW', 'n/a', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (293, 'JPM^H', 'Finance', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (294, 'LTC', 'Consumer Services', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (295, 'ALX', 'Consumer Services', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (296, 'IIVI', 'Capital Goods', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (297, 'EFII', 'Technology', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (298, 'MKL', 'Finance', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (299, 'POLA', 'n/a', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (300, 'VBF', 'n/a', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (301, 'CPAC', 'Capital Goods', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (302, 'NAV^D', 'Capital Goods', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (303, 'ECL', 'Basic Industries', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (304, 'CHA', 'Public Utilities', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (305, 'CDXC', 'Consumer Durables', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (306, 'STRT', 'Capital Goods', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (307, 'UHT', 'Consumer Services', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (308, 'AUPH', 'Health Care', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (309, 'AEO', 'Consumer Services', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (310, 'RCMT', 'Technology', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (311, 'HCKT', 'Consumer Services', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (312, 'F', 'Capital Goods', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (313, 'WLK', 'Basic Industries', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (314, 'GOF', 'n/a', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (315, 'VALE', 'Basic Industries', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (316, 'TESO', 'Energy', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (317, 'FUN', 'Consumer Services', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (318, 'RJF', 'Finance', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (319, 'PSC', 'n/a', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (320, 'MOV', 'Consumer Non-Durables', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (321, 'TTC', 'Capital Goods', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (322, 'MPWR', 'Technology', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (323, 'KIM^K', 'n/a', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (324, 'GGP', 'Consumer Services', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (325, 'XRX', 'Miscellaneous', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (326, 'CRMT', 'Consumer Durables', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (327, 'ESGG', 'n/a', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (328, 'HYT', 'n/a', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (329, 'DFRG', 'Consumer Services', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (330, 'CLR', 'Energy', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (331, 'NDSN', 'Capital Goods', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (332, 'MPW', 'Consumer Services', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (333, 'FEO', 'n/a', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (334, 'LSTR', 'Transportation', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (335, 'CCL', 'Consumer Services', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (336, 'APU', 'Consumer Services', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (337, 'SBNY', 'Finance', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (338, 'LEE', 'Consumer Services', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (339, 'MOS', 'Basic Industries', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (340, 'AHPI', 'Health Care', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (341, 'GAB^G', 'n/a', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (342, 'JSMD', 'n/a', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (343, 'LINC', 'Consumer Services', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (344, 'CONN', 'Consumer Services', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (345, 'EGAN', 'Technology', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (346, 'AKTS', 'Public Utilities', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (347, 'FLS', 'Capital Goods', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (348, 'RIO', 'Basic Industries', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (349, 'SPB           ', 'Miscellaneous', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (350, 'LPLA', 'Finance', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (351, 'WIT', 'Technology', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (352, 'TSLA', 'Capital Goods', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (353, 'HMLP', 'Consumer Services', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (354, 'TAC', 'Public Utilities', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (355, 'PAACR', 'Finance', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (356, 'ANH^B', 'n/a', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (357, 'WFC^X', 'n/a', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (358, 'UNXL', 'Capital Goods', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (359, 'SFL', 'Transportation', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (360, 'SIGM', 'Technology', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (361, 'FFA', 'n/a', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (362, 'GBT', 'Health Care', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (363, 'SAIA', 'Transportation', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (364, 'BOSC', 'Technology', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (365, 'GPIA', 'Consumer Durables', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (366, 'ASB^D', 'n/a', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (367, 'ENJ', 'Public Utilities', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (368, 'MCV', 'n/a', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (369, 'SRCE', 'Finance', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (370, 'SLAB', 'Technology', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (371, 'IFGL', 'n/a', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (372, 'JNP', 'Health Care', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (373, 'GENE', 'Health Care', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (374, 'IHIT', 'n/a', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (375, 'MKSI', 'Capital Goods', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (376, 'FORD', 'Consumer Non-Durables', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (377, 'VLO', 'Energy', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (378, 'PRE^G', 'n/a', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (379, 'JPM^G', 'n/a', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (380, 'DDF', 'n/a', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (381, 'MANT', 'Consumer Services', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (382, 'HTBK', 'Finance', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (383, 'LECO', 'Technology', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (384, 'GDL^B', 'n/a', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (385, 'TCBIP', 'Finance', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (386, 'APC', 'Energy', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (387, 'PI', 'Capital Goods', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (388, 'ROIC', 'Consumer Services', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (389, 'EFII', 'Technology', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (390, 'MOFG', 'Finance', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (391, 'HR', 'Consumer Services', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (392, 'ARDC', 'n/a', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (393, 'AMD', 'Technology', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (394, 'NP', 'Basic Industries', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (395, 'WES', 'Public Utilities', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (396, 'IMPV', 'Technology', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (397, 'IDRA', 'Health Care', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (398, 'FBHS', 'Basic Industries', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (399, 'CONN', 'Consumer Services', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (400, 'FSLR', 'Technology', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (401, 'PSO', 'Consumer Services', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (402, 'B', 'Capital Goods', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (403, 'CRM', 'Technology', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (404, 'YRCW', 'Transportation', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (405, 'EAE', 'Public Utilities', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (406, 'MGA', 'Capital Goods', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (407, 'PSA', 'Consumer Services', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (408, 'BIT', 'n/a', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (409, 'NMI', 'n/a', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (410, 'RBC', 'Consumer Durables', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (411, 'CCRC', 'Miscellaneous', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (412, 'HII', 'Capital Goods', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (413, 'SGLB', 'Consumer Durables', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (414, 'ELGX', 'Health Care', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (415, 'OXLCO', 'n/a', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (416, 'PCK', 'n/a', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (417, 'GWB', 'Finance', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (418, 'CDE', 'Basic Industries', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (419, 'MSCI', 'Miscellaneous', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (420, 'PFSW', 'Miscellaneous', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (421, 'ITW', 'Technology', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (422, 'FFKT', 'Finance', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (423, 'XGTI', 'Consumer Durables', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (424, 'TOO^A', 'n/a', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (425, 'JAKK', 'Consumer Non-Durables', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (426, 'QDEL', 'Health Care', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (427, 'LMIA', 'Capital Goods', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (428, 'SBBC', 'Transportation', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (429, 'UBP^G', 'n/a', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (430, 'ZAYO', 'Public Utilities', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (431, 'TCBIL', 'Finance', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (432, 'JOE', 'Consumer Services', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (433, 'RIG', 'Energy', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (434, 'BANF', 'Finance', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (435, 'PSA^A', 'n/a', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (436, 'OASM', 'Health Care', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (437, 'ENIC', 'Public Utilities', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (438, 'NRIM', 'Finance', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (439, 'SHOS', 'Consumer Services', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (440, 'ELP', 'Public Utilities', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (441, 'OEC', 'Basic Industries', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (442, 'FSM', 'Basic Industries', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (443, 'FULLL', 'n/a', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (444, 'MCN', 'n/a', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (445, 'BATRA', 'Consumer Services', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (446, 'GOODO', 'Consumer Services', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (447, 'SLRA', 'n/a', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (448, 'SVU', 'Consumer Non-Durables', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (449, 'ZAIS', 'Finance', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (450, 'FLC', 'n/a', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (451, 'COLM', 'Consumer Non-Durables', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (452, 'DVMT', 'Technology', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (453, 'SNAK', 'Consumer Non-Durables', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (454, 'HOTRW', 'Consumer Services', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (455, 'PCSB', 'Finance', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (456, 'SBNY', 'Finance', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (457, 'OC', 'Capital Goods', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (458, 'EDGW', 'Technology', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (459, 'FICO', 'Miscellaneous', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (460, 'SQZZ', 'n/a', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (461, 'JBHT', 'Transportation', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (462, 'AHP^B', 'n/a', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (463, 'GXP', 'Public Utilities', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (464, 'FLKS', 'Health Care', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (465, 'ENSG', 'Health Care', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (466, 'KODK.WS.A', 'n/a', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (467, 'GLBZ', 'Finance', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (468, 'KEG', 'Energy', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (469, 'RLJE', 'Consumer Services', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (470, 'AREX', 'Energy', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (471, 'PSA^Y', 'n/a', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (472, 'CSGP', 'Miscellaneous', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (473, 'UIHC', 'Finance', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (474, 'FBC', 'Finance', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (475, 'SMHI', 'Transportation', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (476, 'HVT', 'Consumer Services', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (477, 'BXP^B', 'n/a', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (478, 'LBTYB', 'Consumer Services', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (479, 'GTS', 'Finance', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (480, 'PTHN', 'Health Care', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (481, 'WSM', 'Consumer Services', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (482, 'SN', 'Energy', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (483, 'ELS', 'Consumer Services', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (484, 'CDTX', 'Health Care', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (485, 'EPR^E', 'n/a', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (486, 'HSBC', 'Finance', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (487, 'OPK', 'Health Care', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (488, 'AVIR', 'Health Care', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (489, 'OPHC', 'Finance', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (490, 'MUSA', 'Consumer Durables', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (491, 'PFBI', 'Finance', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (492, 'OKTA', 'Technology', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (493, 'DMB', 'n/a', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (494, 'KURA', 'Health Care', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (495, 'KE', 'Technology', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (496, 'UGP', 'Public Utilities', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (497, 'GPT', 'Consumer Services', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (498, 'ITEK', 'Health Care', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (499, 'VNO^G', 'n/a', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (500, 'HRI', 'n/a', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (501, 'PWR', 'Capital Goods', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (502, 'CBPX', 'Capital Goods', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (503, 'TARO', 'Health Care', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (504, 'FHY', 'n/a', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (505, 'BLKB', 'Technology', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (506, 'NYLD.A', 'n/a', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (507, 'FLC', 'n/a', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (508, 'USG', 'Capital Goods', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (509, 'DFP', 'n/a', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (510, 'AGU', 'Basic Industries', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (511, 'JSYNU', 'Finance', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (512, 'PKE', 'Technology', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (513, 'INTG', 'Consumer Services', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (514, 'BVXVW', 'Health Care', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (515, 'IFV', 'n/a', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (516, 'NXQ', 'n/a', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (517, 'CASY', 'Consumer Durables', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (518, 'TEAR', 'Health Care', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (519, 'CTRP', 'Miscellaneous', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (520, 'UCFC', 'Finance', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (521, 'GFED', 'Finance', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (522, 'ETV', 'n/a', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (523, 'TRN', 'Capital Goods', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (524, 'BIP', 'Consumer Services', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (525, 'LULU', 'Consumer Non-Durables', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (526, 'FOXA', 'Consumer Services', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (527, 'RCL', 'Consumer Services', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (528, 'ICBK', 'Finance', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (529, 'UTX', 'Capital Goods', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (530, 'AMRI', 'Health Care', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (531, 'SQNS', 'Technology', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (532, 'VRA', 'Consumer Non-Durables', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (533, 'LVNTB', 'Consumer Services', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (534, 'NTC', 'n/a', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (535, 'TGP^A', 'n/a', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (536, 'CARB', 'Technology', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (537, 'RRTS', 'Transportation', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (538, 'JRJC', 'Finance', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (539, 'KNDI', 'Capital Goods', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (540, 'WCST', 'Consumer Services', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (541, 'FRA', 'n/a', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (542, 'RVLT', 'Consumer Durables', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (543, 'PAGG', 'n/a', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (544, 'GENY', 'n/a', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (545, 'HMST', 'Finance', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (546, 'GDV', 'n/a', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (547, 'TOUR', 'Consumer Services', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (548, 'CFR^A', 'n/a', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (549, 'DXC', 'Technology', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (550, 'CMG', 'Consumer Services', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (551, 'BANC', 'Finance', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (552, 'OGXI', 'Health Care', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (553, 'MLM', 'Basic Industries', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (554, 'KONE', 'Technology', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (555, 'SFR', 'Consumer Services', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (556, 'MD', 'Health Care', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (557, 'MRNS', 'Health Care', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (558, 'BPOPN', 'Finance', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (559, 'DSKEW', 'Consumer Services', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (560, 'BHVN', 'Health Care', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (561, 'SITO', 'Miscellaneous', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (562, 'STAG^B', 'n/a', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (563, 'AAOI', 'Technology', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (564, 'DSU', 'n/a', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (565, 'INSG', 'Consumer Durables', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (566, 'RSYS', 'Technology', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (567, 'HSEB', 'Finance', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (568, 'FSZ', 'n/a', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (569, 'PZN', 'Finance', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (570, 'FGL', 'Finance', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (571, 'AXR', 'Consumer Services', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (572, 'HOG', 'Consumer Non-Durables', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (573, 'TEP', 'Public Utilities', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (574, 'HYH', 'Health Care', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (575, 'VUZI', 'Technology', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (576, 'GPACW', 'Health Care', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (577, 'DVN', 'Energy', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (578, 'RT', 'Consumer Services', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (579, 'BFK', 'n/a', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (580, 'FLWS', 'Consumer Services', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (581, 'ENBL', 'Public Utilities', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (582, 'GECC', 'n/a', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (583, 'ICD', 'Energy', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (584, 'ING', 'Finance', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (585, 'NGHCZ', 'Finance', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (586, 'SGYP', 'Health Care', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (587, 'LARK', 'Finance', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (588, 'MNK', 'Health Care', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (589, 'MDGS', 'Health Care', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (590, 'ATHN', 'Miscellaneous', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (591, 'NK', 'Health Care', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (592, 'SPG^J', 'n/a', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (593, 'TST', 'Consumer Services', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (594, 'SUNS', 'n/a', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (595, 'PME', 'n/a', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (596, 'BKCC', 'n/a', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (597, 'HGV', 'Consumer Services', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (598, 'FDUS', 'n/a', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (599, 'EVF', 'n/a', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (600, 'VCIT', 'n/a', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (601, 'UZB', 'Public Utilities', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (602, 'UVSP', 'Finance', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (603, 'ACWX', 'n/a', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (604, 'TAP.A', 'n/a', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (605, 'HI', 'Consumer Durables', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (606, 'JASN', 'Consumer Durables', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (607, 'COR', 'Consumer Services', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (608, 'PGJ', 'n/a', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (609, 'LMRKP', 'Consumer Services', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (610, 'PMF', 'n/a', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (611, 'FENX', 'Consumer Services', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (612, 'PFI', 'n/a', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (613, 'MELI', 'Miscellaneous', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (614, 'FUSB', 'Finance', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (615, 'WPRT', 'Energy', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (616, 'MMS', 'Miscellaneous', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (617, 'HBI', 'Consumer Services', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (618, 'GJV', 'Finance', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (619, 'GNL', 'Consumer Services', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (620, 'BIIB', 'Health Care', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (621, 'KMPA', 'Finance', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (622, 'JPM.WS', 'n/a', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (623, 'CHCI', 'Capital Goods', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (624, 'FORM', 'Technology', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (625, 'NSL', 'n/a', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (626, 'XKE', 'Finance', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (627, 'BRC', 'Consumer Durables', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (628, 'NGL', 'Energy', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (629, 'AJRD', 'Capital Goods', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (630, 'NAVG', 'Finance', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (631, 'SMSI', 'Technology', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (632, 'AXGN', 'Health Care', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (633, 'MNI', 'Consumer Services', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (634, 'CFFI', 'Finance', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (635, 'BABY', 'Health Care', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (636, 'ADRO', 'Health Care', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (637, 'EMCB', 'n/a', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (638, 'ADRO', 'Health Care', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (639, 'BPMC', 'Health Care', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (640, 'KMX', 'Consumer Durables', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (641, 'ARRS', 'Technology', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (642, 'LGCYP', 'Energy', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (643, 'TERP', 'Public Utilities', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (644, 'FIX', 'Capital Goods', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (645, 'DTYS', 'Finance', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (646, 'SMFG', 'Finance', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (647, 'VRSK', 'Technology', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (648, 'RVNC', 'Health Care', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (649, 'CBL^E', 'n/a', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (650, 'VCV', 'n/a', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (651, 'CELH', 'Consumer Non-Durables', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (652, 'AREX', 'Energy', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (653, 'K', 'Consumer Non-Durables', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (654, 'GPIC', 'Consumer Non-Durables', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (655, 'ACWI', 'n/a', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (656, 'BLX', 'Finance', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (657, 'COHU', 'Capital Goods', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (658, 'ENO', 'Public Utilities', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (659, 'TACT', 'Technology', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (660, 'WDAY', 'Technology', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (661, 'FEI           ', 'n/a', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (662, 'DGX', 'Health Care', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (663, 'III', 'Consumer Services', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (664, 'HCCI', 'Basic Industries', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (665, 'LILA', 'Consumer Services', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (666, 'JPM^F', 'n/a', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (667, 'ADX', 'n/a', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (668, 'LANC', 'Consumer Non-Durables', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (669, 'MMS', 'Miscellaneous', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (670, 'REG^G', 'n/a', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (671, 'AXDX', 'Capital Goods', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (672, 'RAS', 'Consumer Services', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (673, 'CASC', 'Health Care', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (674, 'VEDL', 'Capital Goods', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (675, 'NUS', 'Health Care', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (676, 'TLYS', 'Consumer Services', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (677, 'WSFSL', 'Finance', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (678, 'LNGR', 'n/a', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (679, 'HBI', 'Consumer Services', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (680, 'ESGD', 'n/a', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (681, 'FIG', 'Finance', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (682, 'DSGX', 'Technology', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (683, 'SGBX', 'n/a', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (684, 'SCE^G', 'n/a', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (685, 'CSL', 'Basic Industries', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (686, 'HOLX', 'Health Care', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (687, 'USB^O', 'n/a', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (688, 'GPX', 'Consumer Services', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (689, 'INN^C', 'n/a', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (690, 'WMLP', 'Energy', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (691, 'DTEA', 'Consumer Non-Durables', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (692, 'GECC', 'n/a', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (693, 'EPAY', 'Technology', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (694, 'ARDX', 'Health Care', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (695, 'ANGO', 'Health Care', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (696, 'AMRB', 'Finance', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (697, 'PKBK', 'Finance', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (698, 'RYAM^A', 'n/a', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (699, 'WFM', 'Consumer Services', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (700, 'GPK', 'Consumer Durables', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (701, 'NLST', 'Technology', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (702, 'ECC           ', 'n/a', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (703, 'GNT', 'n/a', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (704, 'SOHOM', 'Consumer Services', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (705, 'AGNCB', 'Consumer Services', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (706, 'HAL', 'Energy', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (707, 'LVHD', 'n/a', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (708, 'PTNR', 'Public Utilities', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (709, 'CENX', 'Basic Industries', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (710, 'LTBR', 'Consumer Services', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (711, 'HDNG', 'Capital Goods', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (712, 'EGY', 'Energy', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (713, 'CXSE', 'n/a', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (714, 'ROK', 'Capital Goods', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (715, 'PLBC', 'Finance', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (716, 'AAPC', 'Consumer Services', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (717, 'IIVI', 'Capital Goods', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (718, 'LEXEB', 'Consumer Services', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (719, 'SBRAP', 'Consumer Services', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (720, 'PL^E', 'n/a', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (721, 'DISCA', 'Consumer Services', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (722, 'BTZ', 'n/a', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (723, 'MH^A', 'n/a', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (724, 'KMX', 'Consumer Durables', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (725, 'BLKB', 'Technology', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (726, 'TTMI', 'Technology', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (727, 'ZBIO', 'n/a', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (728, 'HBI', 'Consumer Services', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (729, 'SSNI', 'Technology', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (730, 'WHLRP', 'Consumer Services', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (731, 'DOV', 'Technology', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (732, 'YERR', 'Finance', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (733, 'DLR', 'Consumer Services', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (734, 'FOMX', 'Consumer Durables', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (735, 'OSBC', 'Finance', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (736, 'PLXS', 'Technology', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (737, 'BGH', 'n/a', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (738, 'ELC', 'Public Utilities', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (739, 'JASNW', 'Consumer Durables', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (740, 'FTRPR', 'Public Utilities', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (741, 'INN^D', 'n/a', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (742, 'JASO', 'Technology', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (743, 'RFTA', 'Consumer Services', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (744, 'PBSK', 'Finance', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (745, 'ASB^D', 'n/a', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (746, 'CDL', 'n/a', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (747, 'XPLR', 'Technology', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (748, 'NUVA', 'Health Care', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (749, 'WTFCW', 'Finance', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (750, 'NVO', 'Health Care', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (751, 'SPAN', 'Health Care', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (752, 'EAGLW', 'Finance', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (753, 'AWRE', 'Technology', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (754, 'ROCK', 'Capital Goods', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (755, 'CMRX', 'Health Care', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (756, 'HBK', 'Finance', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (757, 'NTEC', 'Health Care', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (758, 'QTWO', 'Technology', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (759, 'AR', 'Energy', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (760, 'STFC', 'Finance', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (761, 'NBB', 'n/a', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (762, 'PCG', 'Public Utilities', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (763, 'SCE^K', 'n/a', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (764, 'PSA^E', 'Consumer Services', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (765, 'FLWS', 'Consumer Services', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (766, 'STT^E', 'n/a', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (767, 'SFM', 'Consumer Services', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (768, 'UONEK', 'Consumer Services', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (769, 'TI', 'Consumer Services', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (770, 'SOV^C', 'n/a', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (771, 'XPLR', 'Technology', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (772, 'VR', 'Finance', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (773, 'AGCO', 'Capital Goods', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (774, 'CDNA', 'Health Care', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (775, 'NOAH', 'Finance', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (776, 'NUV', 'n/a', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (777, 'TV', 'Consumer Services', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (778, 'FONE', 'n/a', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (779, 'MINDP', 'Technology', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (780, 'LDRI', 'n/a', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (781, 'ENO', 'Public Utilities', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (782, 'SP', 'Consumer Services', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (783, 'PEB^C', 'n/a', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (784, 'FMC', 'Basic Industries', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (785, 'PROV', 'Finance', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (786, 'IDSA', 'Consumer Durables', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (787, 'GARS', 'n/a', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (788, 'ETY', 'n/a', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (789, 'VEACU', 'Finance', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (790, 'TDJ', 'Public Utilities', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (791, 'DK', 'Energy', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (792, 'OXFD', 'Health Care', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (793, 'SEMG', 'Energy', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (794, 'MKC', 'Consumer Non-Durables', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (795, 'CLI', 'Consumer Services', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (796, 'CPS', 'Capital Goods', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (797, 'CPAAW', 'Finance', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (798, 'AAN', 'Technology', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (799, 'CHY', 'n/a', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (800, 'WLL', 'Energy', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (801, 'LULU', 'Consumer Non-Durables', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (802, 'SWZ', 'n/a', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (803, 'GGM', 'n/a', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (804, 'JCI', 'Consumer Services', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (805, 'LMHA', 'Finance', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (806, 'WNS', 'Miscellaneous', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (807, 'OFIX', 'Health Care', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (808, 'VG', 'Public Utilities', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (809, 'NMI', 'n/a', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (810, 'TGP^A', 'n/a', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (811, 'CTRL', 'Capital Goods', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (812, 'AXR', 'Consumer Services', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (813, 'SCI', 'Consumer Services', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (814, 'GNTX', 'Capital Goods', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (815, 'HYB', 'n/a', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (816, 'CLNS^F.CL', 'n/a', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (817, 'MEN', 'n/a', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (818, 'EVBG', 'n/a', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (819, 'RILYL', 'Miscellaneous', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (820, 'HSII', 'Technology', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (821, 'FNHC', 'Finance', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (822, 'ARE^D', 'n/a', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (823, 'HIW', 'Consumer Services', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (824, 'PBA', 'Energy', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (825, 'FUSB', 'Finance', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (826, 'ABDC', 'n/a', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (827, 'CSTE', 'Capital Goods', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (828, 'PL^E', 'n/a', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (829, 'CHL', 'Public Utilities', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (830, 'UBNK', 'Finance', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (831, 'VIAB', 'Consumer Services', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (832, 'CETXP', 'Capital Goods', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (833, 'HRG', 'Miscellaneous', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (834, 'DWIN', 'n/a', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (835, 'WRB^C', 'n/a', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (836, 'TPB', 'Consumer Non-Durables', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (837, 'PRE^I', 'n/a', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (838, 'IVENC', 'n/a', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (839, 'AMWD', 'Basic Industries', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (840, 'DXB', 'Finance', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (841, 'ONCE', 'Health Care', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (842, 'QRHC', 'Technology', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (843, 'CZR', 'Consumer Services', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (844, 'TLI', 'n/a', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (845, 'CTRN', 'Consumer Services', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (846, 'AVB', 'Consumer Services', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (847, 'NETE', 'Technology', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (848, 'UONEK', 'Consumer Services', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (849, 'ADP', 'Technology', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (850, 'AFW.CL', 'n/a', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (851, 'KTP', 'Finance', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (852, 'JE', 'Public Utilities', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (853, 'ANDA', 'Finance', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (854, 'BSAC', 'Finance', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (855, 'HIL', 'Consumer Services', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (856, 'PNF', 'n/a', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (857, 'FRED', 'Consumer Services', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (858, 'GLOG', 'Consumer Services', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (859, 'CPRX', 'Health Care', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (860, 'CDXC', 'Consumer Durables', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (861, 'CNHI', 'Capital Goods', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (862, 'TLRD', 'Consumer Services', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (863, 'EVH', 'Consumer Services', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (864, 'HL^B', 'Basic Industries', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (865, 'CYRXW', 'Transportation', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (866, 'GCV', 'n/a', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (867, 'NANO', 'Capital Goods', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (868, 'MCC', 'n/a', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (869, 'EBR', 'Public Utilities', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (870, 'PWE', 'Energy', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (871, 'MATR', 'Technology', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (872, 'MTH', 'Capital Goods', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (873, 'AHT^D', 'n/a', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (874, 'APOG', 'Capital Goods', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (875, 'JJSF', 'Consumer Non-Durables', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (876, 'UEIC', 'Consumer Non-Durables', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (877, 'BF.A', 'n/a', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (878, 'BBD', 'Finance', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (879, 'MBWM', 'Finance', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (880, 'VBND', 'n/a', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (881, 'MDCO', 'Health Care', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (882, 'BPFHW', 'Finance', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (883, 'BLMN', 'Consumer Services', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (884, 'IMMY', 'Health Care', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (885, 'VMW', 'Technology', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (886, 'VONE', 'n/a', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (887, 'CNA', 'Finance', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (888, 'DNOW', 'Energy', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (889, 'ASUR', 'Technology', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (890, 'TEGP', 'Public Utilities', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (891, 'SBNY', 'Finance', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (892, 'RACE', 'Capital Goods', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (893, 'AIV', 'Consumer Services', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (894, 'BMRN', 'Health Care', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (895, 'GMZ', 'n/a', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (896, 'EMCI', 'Finance', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (897, 'BLRX', 'Health Care', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (898, 'SM', 'Energy', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (899, 'CLDC', 'Finance', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (900, 'ZIOP', 'Health Care', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (901, 'DLR^I', 'n/a', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (902, 'KB', 'Finance', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (903, 'ARTW', 'Capital Goods', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (904, 'ERF', 'Energy', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (905, 'SJR', 'Consumer Services', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (906, 'SRV', 'n/a', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (907, 'UONE', 'Consumer Services', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (908, 'MCD', 'Consumer Services', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (909, 'USFD', 'Consumer Non-Durables', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (910, 'BOX', 'Technology', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (911, 'DM', 'Public Utilities', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (912, 'SXC', 'Basic Industries', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (913, 'HPS', 'n/a', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (914, 'TRK', 'Consumer Services', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (915, 'TPVG', 'n/a', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (916, 'ARCH', 'Energy', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (917, 'EAE', 'Public Utilities', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (918, 'SOXX', 'n/a', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (919, 'LGIH', 'Capital Goods', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (920, 'KMI', 'Public Utilities', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (921, 'NDRM', 'Health Care', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (922, 'DAIO', 'Capital Goods', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (923, 'WVVI', 'Consumer Non-Durables', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (924, 'FLC', 'n/a', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (925, 'AINV', 'n/a', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (926, 'RFAP', 'n/a', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (927, 'DEST', 'Consumer Services', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (928, 'GLBR', 'Finance', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (929, 'LXFR', 'Basic Industries', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (930, 'CSL', 'Basic Industries', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (931, 'CFCO', 'Finance', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (932, 'BONT', 'Consumer Services', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (933, 'KO', 'Consumer Non-Durables', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (934, 'WPPGY', 'Technology', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (935, 'Z', 'Miscellaneous', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (936, 'TWO', 'Consumer Services', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (937, 'JMM', 'n/a', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (938, 'COR^A', 'n/a', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (939, 'MNP', 'n/a', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (940, 'WFC^N', 'n/a', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (941, 'CF', 'Basic Industries', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (942, 'CHCT', 'Consumer Services', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (943, 'SANM', 'Technology', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (944, 'PEIX', 'Basic Industries', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (945, 'CSML', 'n/a', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (946, 'BIB', 'n/a', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (947, 'ONVO', 'Health Care', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (948, 'CVGI', 'Capital Goods', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (949, 'FRC^E', 'n/a', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (950, 'CCBG', 'Finance', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (951, 'BHK', 'n/a', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (952, 'CHD', 'Basic Industries', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (953, 'PRLB', 'Capital Goods', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (954, 'HES^A', 'n/a', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (955, 'CRTN', 'Consumer Services', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (956, 'PYDS', 'Finance', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (957, 'ALL^E', 'n/a', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (958, 'EMN', 'Basic Industries', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (959, 'BKT', 'n/a', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (960, 'WWE', 'Consumer Services', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (961, 'CSOD', 'Technology', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (962, 'SRUNU', 'Finance', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (963, 'AJRD', 'Capital Goods', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (964, 'ASV', 'Capital Goods', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (965, 'OGXI', 'Health Care', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (966, 'CIG', 'Public Utilities', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (967, 'DISCK', 'Consumer Services', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (968, 'GLOP^A', 'n/a', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (969, 'LEN', 'Basic Industries', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (970, 'ALL^F', 'n/a', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (971, 'ZUMZ', 'Consumer Services', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (972, 'RP', 'Technology', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (973, 'NRP', 'Energy', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (974, 'SVBI', 'Finance', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (975, 'CPAA', 'Finance', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (976, 'STDY', 'Health Care', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (977, 'IMKTA', 'Consumer Services', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (978, 'XL', 'Finance', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (979, 'TPX', 'Consumer Durables', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (980, 'AHL^C', 'n/a', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (981, 'TEN', 'Capital Goods', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (982, 'CTBB', 'Public Utilities', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (983, 'EOI', 'n/a', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (984, 'RBS^L', 'n/a', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (985, 'IGI', 'n/a', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (986, 'RAI', 'Consumer Non-Durables', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (987, 'BSPM', 'Health Care', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (988, 'ASUR', 'Technology', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (989, 'PNI', 'n/a', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (990, 'DTJ', 'Public Utilities', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (991, 'PDCE', 'Energy', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (992, 'HSC', 'Capital Goods', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (993, 'RUBI', 'Technology', 1);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (994, 'LGCYP', 'Energy', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (995, 'VECO', 'Technology', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (996, 'PETX', 'Health Care', 3);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (997, 'NPO', 'Basic Industries', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (998, 'SQNS', 'Technology', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (999, 'NXQ', 'n/a', 2);
insert into MOCK_DATA (id, codigoCurso, NombreCurso, estado) values (1000, 'FCFS', 'Consumer Services', 1);
